### ISSUE TITLE
Mettre un en place le CRUD pour les posts et commentaire

### ISSUE THREAD

**Issue by k-saidou** [k-saidou/Blog-PHP#14]
CRUD pour les commentaires : l'utilisateur inscrit peut commenter et l'admin valide, supprime ou modifie le commentaire avant affichage.
CRUD pour les post: Seul l'admin y a accès.

**Comment by tecuzin** [comment]
@k-saidou ne pas oublier les cas de tests
- avec POSTman je peux envoyer une requête GET pour récupérer des posts et commentaires
- avec POSTman je peux envoyer une requête POST pour créer, modifier des posts et commentaires
- avec POSTman je peux envoyer une requête POST ou DELETE pour créer, modifier des posts et commentaires

**Sinon par URL**
https://localhost/(post)/(opération)
https://localhost/(post)/(commentaire)/(opération)
