### ISSUE TITLE
Créer la page affichant un blog post

### ISSUE THREAD

**Issue by k-saidou** [k-saidou/Blog-PHP#3]
Détail d’un blog post, il faut afficher les informations suivantes :

le titre ;
le chapô ;
le contenu ;
l’auteur ;
la date de dernière mise à jour ;
le formulaire permettant d’ajouter un commentaire (soumis pour validation) ;
les listes des commentaires validés et publiés.

**Comment by tecuzin** [comment]
- éditeur de code 
- difficulté : organisation de la récupération de données
- "je sais à peu près comment procéder", besoin d'un peu de recherche
